// Official Verified Baseline Statutory Registry for LM-TRACE Offline & Standalone Resilience

import 'models/statutory_models.dart';

final StatutorySummaryModel kStatutorySummaryBaseline = StatutorySummaryModel(
  totalDocuments: 8,
  activeDocuments: 7,
  amendmentDocuments: 5,
  scheduledDocuments: 1,
  totalStatutoryRules: 9,
  activeStatutoryRules: 8,
  scheduledRules: 1,
  automatedRulesCount: 5,
  unautomatedRulesCount: 4,
  ruleFamilies: [
    'The Legal Metrology Act, 2009',
    'Legal Metrology (Packaged Commodities) Rules',
  ],
  jurisdiction: 'Union of India (Central DCA)',
  lastStatutoryUpdate: '2026-09-10T00:00:00Z',
);

final List<StatutoryDocumentModel> kStatutoryDocumentsBaseline = [
  StatutoryDocumentModel(
    id: 'doc-lm-act-2009',
    title: 'The Legal Metrology Act, 2009 (Act No. 1 of 2010)',
    shortTitle: 'The Legal Metrology Act, 2009',
    documentType: 'ACT',
    authority: 'Parliament of India / Ministry of Consumer Affairs',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'Act No. 1 of 2010',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 1, No. 1',
    publicationDate: '2010-01-14T00:00:00Z',
    effectiveDate: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/act_2009.pdf',
    version: '2009.1',
    ruleFamily: 'The Legal Metrology Act, 2009',
    summary: 'The primary parliamentary statute establishing and enforcing standards of weights and measures, regulating trade and commerce in pre-packaged commodities, and prescribing statutory penalties.',
    rulesCount: 2,
  ),
  StatutoryDocumentModel(
    id: 'doc-pc-rules-2011',
    title: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    shortTitle: 'LM (Packaged Commodities) Rules, 2011',
    documentType: 'RULES',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'G.S.R. 202(E)',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 3(i), No. 147',
    publicationDate: '2011-03-07T00:00:00Z',
    effectiveDate: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/pcr2011.pdf',
    version: '2024.1',
    parentDocumentId: 'doc-lm-act-2009',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Principal statutory rules detailing mandatory packaging declarations (Rule 6), Table-I character font height proportions (Rule 7), legibility standards (Rule 9), and standard packaging sizes.',
    rulesCount: 5,
  ),
  StatutoryDocumentModel(
    id: 'doc-amend-2017-ecom',
    title: 'Legal Metrology (Packaged Commodities) (Amendment) Rules, 2017 (E-Commerce Provisions)',
    shortTitle: 'E-Commerce Amendment Rules, 2017',
    documentType: 'GAZETTE_AMENDMENT',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'G.S.R. 629(E)',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 3(i), No. 518',
    publicationDate: '2017-06-23T00:00:00Z',
    effectiveDate: '2018-01-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/gsr_629.pdf',
    version: '2018.1',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Enacted sub-rule (10) under Rule 6 requiring all marketplace and inventory e-commerce entities to display mandatory packaging declarations digitally prior to customer purchase.',
    rulesCount: 1,
  ),
  StatutoryDocumentModel(
    id: 'doc-amend-2021',
    title: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021 (Unit Sale Price Mandate)',
    shortTitle: 'Unit Sale Price Amendment, 2021',
    documentType: 'GAZETTE_AMENDMENT',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'G.S.R. 779(E)',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 3(i), No. 648',
    publicationDate: '2021-11-02T00:00:00Z',
    effectiveDate: '2022-12-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/gsr_779.pdf',
    version: '2022.1',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Mandated Unit Sale Price (USP) across packaged goods in terms of ₹ per g / ₹ per ml / ₹ per kg / ₹ per L, alongside retail MRP to protect consumers from deceptive sizing.',
    rulesCount: 1,
  ),
  StatutoryDocumentModel(
    id: 'doc-amend-2022-spare',
    title: 'Legal Metrology (Packaged Commodities) (Second Amendment) Rules, 2022 (Electronic Products)',
    shortTitle: 'Electronic Products Amendment, 2022',
    documentType: 'GAZETTE_AMENDMENT',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'G.S.R. 520(E)',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 3(i), No. 427',
    publicationDate: '2022-07-06T00:00:00Z',
    effectiveDate: '2022-07-06T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/gsr_520.pdf',
    version: '2022.2',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Permitted manufacturers of electronic products to declare non-critical label declarations via QR Code, provided that basic declarations (commodity name, MRP, net quantity, consumer care) remain on the physical label.',
    rulesCount: 1,
  ),
  StatutoryDocumentModel(
    id: 'doc-amend-2023',
    title: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2023 & Jan Vishwas Act Alignment',
    shortTitle: 'Jan Vishwas Alignment Amendment, 2023',
    documentType: 'GAZETTE_AMENDMENT',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'G.S.R. 721(E)',
    gazetteReference: 'Gazette of India, Extraordinary, Part II, Section 3(i), No. 598',
    publicationDate: '2023-10-06T00:00:00Z',
    effectiveDate: '2024-01-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/latest-news',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/gsr_721.pdf',
    version: '2024.1',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Substituted penal provisions under Rule 32 in alignment with the Jan Vishwas (Amendment of Provisions) Act, 2023, shifting technical first-time violations to statutory civil compounding.',
    rulesCount: 1,
  ),
  StatutoryDocumentModel(
    id: 'doc-dca-advisory-2024',
    title: 'Department of Consumer Affairs Enforcement Advisory on E-Commerce Pre-Purchase Disclosures',
    shortTitle: 'DCA E-Commerce Advisory, 2024',
    documentType: 'OFFICIAL_ADVISORY',
    authority: 'Department of Consumer Affairs, Government of India',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'DCA-ADVISORY-2024-ECOM',
    publicationDate: '2024-04-15T00:00:00Z',
    effectiveDate: '2024-05-01T00:00:00Z',
    status: 'ACTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/latest-news',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/advisory_ecom_2024.pdf',
    version: '2024.ECOM',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Mandatory operational advisory directing all e-commerce platforms to ensure pre-purchase declarations (MRP, USP, Country of Origin, Best Before) are displayed above the fold without requiring customer clicks.',
    rulesCount: 1,
  ),
  StatutoryDocumentModel(
    id: 'doc-future-ecom-2027',
    title: 'Strategic Digital Viewport Standard: Machine-Readable QR Synchronization (Scheduled 2027)',
    shortTitle: 'Digital Viewport Standard (Scheduled 2027)',
    documentType: 'PROPOSED_AMENDMENT',
    authority: 'Ministry of Consumer Affairs, Food and Public Distribution',
    jurisdiction: 'Government of India (Union)',
    notificationNumber: 'DCA-PROPOSED-2026/GSR-889',
    gazetteReference: 'Gazette of India, Extraordinary, Draft Notification 889',
    publicationDate: '2026-09-10T00:00:00Z',
    effectiveDate: '2027-07-01T00:00:00Z',
    status: 'NOT_YET_EFFECTIVE',
    sourceUrl: 'https://consumeraffairs.gov.in/pages/latest-news',
    officialDocumentUrl: 'https://consumeraffairs.gov.in/sites/default/files/draft_gsr_889.pdf',
    version: '2027.PROPOSED',
    parentDocumentId: 'doc-pc-rules-2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    summary: 'Future scheduled gazette standard mandating dynamic machine-readable QR verification and real-time backend declaration synchronization on all marketplace listings. Published for advance industry preparedness; effective from 1 July 2027.',
    rulesCount: 1,
  ),
];

final List<StatutoryRuleModel> kStatutoryRulesBaseline = [
  StatutoryRuleModel(
    id: 'stat-act-sec-18',
    ruleCode: 'STAT-ACT-SEC-18',
    documentId: 'doc-lm-act-2009',
    documentTitle: 'The Legal Metrology Act, 2009 (Act No. 1 of 2010)',
    ruleFamily: 'The Legal Metrology Act, 2009',
    ruleNumber: 'Section 18',
    title: 'Declarations on Pre-Packaged Commodities',
    requirementSummary: 'Prohibits manufacture, packing, sale, import, distribution, offering, or exposing for sale of any pre-packaged commodity unless such package bears thereon such declarations and in such manner as may be prescribed.',
    subject: 'Pre-Packaged Commodity Statutory Mandate',
    applicability: 'All commodities in packaged form manufactured, packed, imported, distributed, or sold in India.',
    sourceReference: 'Section 18(1), The Legal Metrology Act, 2009',
    version: '2009.1',
    publicationDate: '2010-01-14T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    isAutomated: false,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-act-sec-36',
    ruleCode: 'STAT-ACT-SEC-36',
    documentId: 'doc-lm-act-2009',
    documentTitle: 'The Legal Metrology Act, 2009 (Act No. 1 of 2010)',
    ruleFamily: 'The Legal Metrology Act, 2009',
    ruleNumber: 'Section 36',
    title: 'Penalty for Selling, etc., of Non-Standard Packages',
    requirementSummary: 'Whoever manufactures, packs, imports, sells, distributes, delivers, or exposes for sale any pre-packaged commodity which does not conform to the declarations on the package shall be punished with fine or compounding.',
    subject: 'Statutory Enforcement & Penalties',
    applicability: 'All manufacturers, packers, importers, and retail distributors.',
    sourceReference: 'Section 36(1) & (2), The Legal Metrology Act, 2009',
    version: '2009.1',
    publicationDate: '2010-01-14T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    isAutomated: false,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-6-decl',
    ruleCode: 'STAT-RULE-6',
    documentId: 'doc-pc-rules-2011',
    documentTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 6(1)',
    title: 'Declarations to be Made on Every Package',
    requirementSummary: 'Every package shall bear legible declarations including: (a) name and address of manufacturer/packer/importer, (b) common/generic name of commodity, (c) net quantity in standard units, (d) month and year of manufacture/packing/import, (e) Maximum Retail Price (MRP) inclusive of all taxes, (f) consumer care details, and (g) sizes/dimensions where applicable.',
    subject: 'Mandatory Label Declarations',
    applicability: 'All retail and pre-packaged commodities sold or offered for sale in India.',
    sourceReference: 'Rule 6(1)(a)-(g), LM (PC) Rules, 2011',
    version: '2024.1',
    publicationDate: '2011-03-07T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-6',
    mappedRuleEngineCode: 'RULE-006',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-6-origin',
    ruleCode: 'STAT-RULE-6-ORIGIN',
    documentId: 'doc-pc-rules-2011',
    documentTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 6(1)(a) & 6(1)(aa)',
    title: 'Manufacturer, Packer, Importer Separation & Country of Origin',
    requirementSummary: 'Requires distinct name and complete address of the manufacturer and, where the manufacturer is not the packer, the name and address of the packer. For imported goods, requires name and address of the importer and the prominent declaration of Country of Origin.',
    subject: 'Entity Traceability & Country of Origin',
    applicability: 'All pre-packaged commodities (domestic and imported).',
    sourceReference: 'Rule 6(1)(a), Rule 6(1)(aa), LM (PC) Rules, 2011',
    version: '2024.1',
    publicationDate: '2011-03-07T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-6',
    mappedRuleEngineCode: 'RULE-006',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-6-usp',
    ruleCode: 'STAT-RULE-6-USP',
    documentId: 'doc-amend-2021',
    documentTitle: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2021 (Unit Sale Price Mandate)',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 6(11)',
    title: 'Mandatory Unit Sale Price (USP) Declaration',
    requirementSummary: 'Mandatory declaration of Unit Sale Price (₹ per g / ₹ per ml / ₹ per kg / ₹ per L / ₹ per item) alongside the retail sale price (MRP) on every retail package where net quantity is more than one number, unit, gram, or millilitre.',
    subject: 'Unit Sale Price (USP)',
    applicability: 'All packaged retail commodities, except packages containing net weight of less than 10g or 10ml.',
    sourceReference: 'Rule 6(11), LM (PC) Rules, 2011 as inserted by G.S.R. 779(E)',
    version: '2022.1',
    publicationDate: '2021-11-02T00:00:00Z',
    effectiveFrom: '2022-12-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-6',
    mappedRuleEngineCode: 'RULE-006-UNIT-SALE-PRICE',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-6-ecom',
    ruleCode: 'STAT-RULE-6-ECOM',
    documentId: 'doc-amend-2017-ecom',
    documentTitle: 'Legal Metrology (Packaged Commodities) (Amendment) Rules, 2017 (E-Commerce Provisions)',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 6(10)',
    title: 'Digital E-Commerce Mandatory Declarations',
    requirementSummary: 'An e-commerce entity shall ensure that the mandatory declarations specified in sub-rule (1) (except month and year of manufacture) are displayed on the digital marketplace product page prior to purchase.',
    subject: 'E-Commerce Marketplace Declarations',
    applicability: 'All e-commerce platforms, marketplaces, and online sellers retailing packaged commodities in India.',
    sourceReference: 'Rule 6(10), LM (PC) Rules, 2011 as inserted by G.S.R. 629(E)',
    version: '2018.1',
    publicationDate: '2017-06-23T00:00:00Z',
    effectiveFrom: '2018-01-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-ecom-2026',
    mappedRuleEngineCode: 'RULE-ECOM-2026',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-7-pdp',
    ruleCode: 'STAT-RULE-7',
    documentId: 'doc-pc-rules-2011',
    documentTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 7 & Table-I',
    title: 'Principal Display Panel (PDP) Dimensions & Minimum Character Height',
    requirementSummary: 'The height of any numeral and letter in the declaration on the Principal Display Panel shall not be less than the minimum height specified in Table-I, calculated strictly based on the area of the Principal Display Panel (cm²).',
    subject: 'PDP Font Height & Area Ratio Proportions',
    applicability: 'All pre-packaged commodities requiring Table-I character proportionality.',
    sourceReference: 'Rule 7(1)-(4) & Table-I, LM (PC) Rules, 2011',
    version: '2024.1',
    publicationDate: '2011-03-07T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-7',
    mappedRuleEngineCode: 'RULE-007',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-9-legibility',
    ruleCode: 'STAT-RULE-9',
    documentId: 'doc-pc-rules-2011',
    documentTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Rule 9',
    title: 'Manner in Which Declarations Shall Be Made (Legibility & Contrast)',
    requirementSummary: 'Every declaration shall be conspicuous, legible, and definitely stated in distinct contrast to the background by font color, embossing, or molding, ensuring clear visibility under normal illumination.',
    subject: 'Conspicuousness, Contrast & Optical Legibility',
    applicability: 'All pre-packaged commodity labels and wrappers.',
    sourceReference: 'Rule 9(1)-(3), LM (PC) Rules, 2011',
    version: '2024.1',
    publicationDate: '2011-03-07T00:00:00Z',
    effectiveFrom: '2011-04-01T00:00:00Z',
    status: 'ACTIVE',
    mappedRuleEngineId: 'rule-9',
    mappedRuleEngineCode: 'RULE-009',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
  ),
  StatutoryRuleModel(
    id: 'stat-rule-future-qr-2027',
    ruleCode: 'STAT-RULE-6-ECOM-2027',
    documentId: 'doc-future-ecom-2027',
    documentTitle: 'Strategic Digital Viewport Standard: Machine-Readable QR Synchronization (Scheduled 2027)',
    ruleFamily: 'Legal Metrology (Packaged Commodities) Rules',
    ruleNumber: 'Proposed Rule 6(12)',
    title: 'Machine-Readable QR Viewport Synchronization Standard (Scheduled 2027)',
    requirementSummary: 'Mandates interactive dynamic QR code validation on digital viewports that synchronizes in real time with the DCA central repository, ensuring no discrepancy between physical package and digital listing. Enforceable from 1 July 2027.',
    subject: 'Machine-Readable Real-Time Listing Verification',
    applicability: 'All e-commerce platforms operating within the territory of India.',
    sourceReference: 'Proposed Rule 6(12), Draft GSR 889',
    version: '2027.PROPOSED',
    publicationDate: '2026-09-10T00:00:00Z',
    effectiveFrom: '2027-07-01T00:00:00Z',
    status: 'NOT_YET_EFFECTIVE',
    mappedRuleEngineId: 'rule-ecom-2027',
    mappedRuleEngineCode: 'RULE-ECOM-2027-QR',
    isAutomated: true,
    officialUrl: 'https://consumeraffairs.gov.in/pages/latest-news',
  ),
];
